[[Xerces]]
arch = "aarch64"
git-tree-sha1 = "2aef78b1d17dbf26549ac8be58ffb34bfbf97786"
os = "macos"

    [[Xerces.download]]
    sha256 = "f21a05241f58273d8113d18dc2c874e0df305b23e944a0fc2c6e208fc38efb9d"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.aarch64-apple-darwin.tar.gz"
[[Xerces]]
arch = "aarch64"
git-tree-sha1 = "ec72f64d22094ca353b44da1ac8ca7148a0e6513"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "485bb826827aa522c35500a8a2a18dd6fd67476dfe21711e77e213ad03e0d6f5"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.aarch64-linux-gnu.tar.gz"
[[Xerces]]
arch = "aarch64"
git-tree-sha1 = "ac49eb8cb93a116b068d2f6915f8d4d2478a975d"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "36e3cc5264df97b38f6df603c8aa2a42fab1e1b3b175de996ace0e71f2704a8c"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.aarch64-linux-musl.tar.gz"
[[Xerces]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d2b221fc78bda5007796848ea2011dab22bee6d"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "402bb516de88485c39e0e4e2c3f5663a75a927e7482e99dd8e9e8570b5b1b837"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.armv6l-linux-gnueabihf.tar.gz"
[[Xerces]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "33fd3298e9fba23398b406c3345dc422e4d1d07f"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "9ccb0265fe415737e7c7e3b76857522648f5b53d5bec056d8c509d0b4a6748a5"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.armv6l-linux-musleabihf.tar.gz"
[[Xerces]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e86ad523f021328fef97ae989db64a1aa048c818"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "c506c672b751740b1cd77acc40dc53c3d9a25e76c536a951a680d3c5a8eaf7e6"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.armv7l-linux-gnueabihf.tar.gz"
[[Xerces]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "745ed83c121f849d6271a97009eefb28c9aaf4e2"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "31a8e9e669d7c6dc9a6d3cbb9362ef6d873ecf77dceae96da3601be48d39ed66"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.armv7l-linux-musleabihf.tar.gz"
[[Xerces]]
arch = "i686"
git-tree-sha1 = "35a3ec13a358c5bf1c65b133895e04824e0cef5a"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "8fda6d65b26aa44d6cf1d08e8d8742617beeb736984afd15c05ce1f9e3bc37c9"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.i686-linux-gnu.tar.gz"
[[Xerces]]
arch = "i686"
git-tree-sha1 = "60b590e3433a5a84699debe208ed4c5f0cc636db"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "3e3ee31cf36e4fa5e84f9b9e3dca8c0a85b2fd71c37a634992da47282f56cd38"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.i686-linux-musl.tar.gz"
[[Xerces]]
arch = "i686"
git-tree-sha1 = "c48c4f2354508c8f64e0646cff9b71e5f8c9f249"
os = "windows"

    [[Xerces.download]]
    sha256 = "eecec05f638061ba6505849b7b3665873f3057bafc581d55140a8be41e1b0f45"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.i686-w64-mingw32.tar.gz"
[[Xerces]]
arch = "powerpc64le"
git-tree-sha1 = "ba3e71cb6e87ccf87db9dda463774ebe4ba7055e"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "39657a26e9d115ebaa69beb379861842fbf3399afb801e41ec2c5bc9148d1f6e"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.powerpc64le-linux-gnu.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "873cac66ad4ed154c44c11514f103918776c832d"
os = "macos"

    [[Xerces.download]]
    sha256 = "1c8ac8fd66520a3896c0e14c0ced206862bb28600a5e5d6738accce8f7c3b96b"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.x86_64-apple-darwin.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "be4a424c0f4b5039931c0360a11944a642db412d"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "39fb6a5ae0f6ea69925d0ee82818426665ef7836b2e2a8cec79d7047714a6989"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.x86_64-linux-gnu.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "49d5b1bdaec1e7a334801c91ba3e8946886a15ed"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "2e41dffda62dbe5bee5ffc2f30450de56e48ae41b4605e699197d63965772684"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.x86_64-linux-musl.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "1e2327b3fbb7b995495bc39a85b44a2da80e3a32"
os = "freebsd"

    [[Xerces.download]]
    sha256 = "dce60739a75699c90bc782a8ec7fd900dbbb61fa4eef304a38686e31712273e7"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.x86_64-unknown-freebsd.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "f31d1f3c1eb3d84ed8d87212e7e856bce8c9e91a"
os = "windows"

    [[Xerces.download]]
    sha256 = "27b782ac4cc4fc97ef45b6e248847f5f9c1fa5819901c064f26819eb87cb90b8"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.4+0/Xerces.v3.2.4.x86_64-w64-mingw32.tar.gz"
