[[Xerces]]
arch = "aarch64"
git-tree-sha1 = "3168e321a78c5f61502c72d38275d34ea99c2153"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "f58826358ba334d5364f979552b01993e27eea8453a7fac6041bd7f61e52a045"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.aarch64-linux-gnu.tar.gz"
[[Xerces]]
arch = "aarch64"
git-tree-sha1 = "6601515d460dcc458658c0b165dc2ce92f431520"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "48a336726fe1d9c9088ed7e72e145f39e3569abb1d796dfce9cced80dfd3965d"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.aarch64-linux-musl.tar.gz"
[[Xerces]]
arch = "armv7l"
git-tree-sha1 = "f68feae631d89b3d7d6c5673797af0af8b989426"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "8a5807b3b3cd569e1c9578c5d4e38c6df80b4981beb0063c858d364063e16cb1"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.armv7l-linux-gnueabihf.tar.gz"
[[Xerces]]
arch = "armv7l"
git-tree-sha1 = "c52046ddd50512e80f7514ce5f41202662f59f78"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "e32c614e44a131b1ffe468935607d9570089a30b235e554a443a7a03e4134027"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.armv7l-linux-musleabihf.tar.gz"
[[Xerces]]
arch = "i686"
git-tree-sha1 = "24012b3a0c7a132a6408ae9def0114c158ebf191"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "690c51d819abed7727dfd9844416fc099a6238ac75f7e05a8a75f5a96f6fcffb"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.i686-linux-gnu.tar.gz"
[[Xerces]]
arch = "i686"
git-tree-sha1 = "a512a43f72abccd92783d8357b41635dd4496e2b"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "4fdfcfa522914b03e602891ab572707fe6d43cfc21dae34185334d2ae06984d0"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.i686-linux-musl.tar.gz"
[[Xerces]]
arch = "i686"
git-tree-sha1 = "d8bc0b1c324c3c48df066ac686517ae491de5880"
os = "windows"

    [[Xerces.download]]
    sha256 = "4dd2d54315395ab3d96992df52e7ea689cf26e782d9e96e95c5cc8fff92f441f"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.i686-w64-mingw32.tar.gz"
[[Xerces]]
arch = "powerpc64le"
git-tree-sha1 = "3074ad4cfd348c1f81197f5db570f37df8219721"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "5c7c721ec3bc505003eb73c0511ea8bd4efd199e72951f1a32f415c176904c1f"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.powerpc64le-linux-gnu.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "a87b0bf6fa8e1360be5b380e6d19fc1ed43d2b71"
os = "macos"

    [[Xerces.download]]
    sha256 = "21411672311cb6b55e02580236ebc61b120a751baa5ed1b6dceba197c93e557b"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.x86_64-apple-darwin14.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "5b3b9c4eb0d1ba327953f18c3448e5d791b67022"
libc = "glibc"
os = "linux"

    [[Xerces.download]]
    sha256 = "ef13a895307b6f6a3f8a6a9489ca38e6f29b1f8ccb997e040e6847e0381fbc5a"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.x86_64-linux-gnu.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "1ae39029ee46e68301b29805413acfe6f86c1fe7"
libc = "musl"
os = "linux"

    [[Xerces.download]]
    sha256 = "442514b0a6c294abbd086c0636a5b55c8f16b1dc4f98cdf841bbb2915c427ba3"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.x86_64-linux-musl.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "52bae1660de2a6fe163b0676538ee4aa3f09f814"
os = "freebsd"

    [[Xerces.download]]
    sha256 = "2fbc2f0d526018fe8fede454a9ff3ef3ee8902814950d2ce93a26757edafc68e"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.x86_64-unknown-freebsd11.1.tar.gz"
[[Xerces]]
arch = "x86_64"
git-tree-sha1 = "5f0c6dfab2911f661bb06741802e3fdd3f1c4179"
os = "windows"

    [[Xerces.download]]
    sha256 = "69115db1a3b36403f92dc60b236391d2f31deae4853181c579f24b0a13b30b6f"
    url = "https://github.com/JuliaBinaryWrappers/Xerces_jll.jl/releases/download/Xerces-v3.2.3+0/Xerces.v3.2.3.x86_64-w64-mingw32.tar.gz"
